name: Test Update Docker Image Tag

on:
  workflow_dispatch:

jobs:
  test-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in package.json
        run: |
          git diff --cached --diff-filter=d package.json || {
            echo "No changes to package.json"
            exit 1
          }
      - name: Get version number from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"

      - name: Checkout AccelBrain-dev__confidential repository
        uses: actions/checkout@v4
        with:
          repository: ChangLijie/AccelBrain-dev__confidential
          ref: test
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: accelbrain-confidential

      - name: Update docker-compose.yml image tag
        run: |
          cd accelbrain-confidential || (echo "Directory not found" && exit 1)
          sed -i "s|innodiskorg/open-webui:.*|innodiskorg/open-webui:v${{ steps.get_version.outputs.version }}|g" docker-compose.yml

      - name: Update CHANGELOG.md
        run: |
          cd accelbrain-confidential
          VERSION="v${{ steps.get_version.outputs.version }}"
          echo "Update CHANGELOG.md with version $VERSION"

          awk -v version="$VERSION" '
          BEGIN { inserted=0 }
          {
            print $0
            if (!inserted && $0 ~ /Semantic Versioning/) {
              print ""
              print "## [" version "] - "
              print ""
              print "### Fixed"
              print ""
              print "- **Update the chatbot to " version "**"
              print ""
              inserted=1
            }
          }' CHANGELOG.md > CHANGELOG.tmp && mv CHANGELOG.tmp CHANGELOG.md
          rm -f CHANGELOG.tmp
          cat CHANGELOG.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump open-webui image to v${{ steps.get_version.outputs.version }}"
          repository: ./accelbrain-confidential